version: '3.8'
services:
  origin:
    build:
        context: ./origin
    ports:
      - "8080:8080"
    networks:
      - cdn_network
  cache:
    depends_on:
      - origin
    build:
      context: ./cache
    ports:
      - "8081:8081"
    networks:
      - cdn_network
  gateway:
    depends_on:
      - cache
    build:
      context: ./gateway
    ports:
      - "8082:8082"
    networks:
      - cdn_network
networks:
    cdn_network:
      name: cdn_network
      driver: bridge
